### ISSUE TITLE
YAML Load warnings 

### ISSUE THREAD

**Issue by cclauss** [internetarchive/infogami#126]
@Purhan Would you be willing to create another PR like internetarchive/openlibrary#3963 to fix similar warnings on this repo? 
* https://github.com/internetarchive/infogami/blob/master/infogami/__init__.py#L168
* https://github.com/internetarchive/infogami/blob/master/infogami/infobase/server.py#L636

**Comment by Purhan** [comment]
Sure, I will create a PR soon.
