### ISSUE TITLE
Upgrade infogami/infobase/client.py from urllib to requests

### ISSUE THREAD

**Issue by cclauss** [internetarchive/infogami#145]
Similar to https://github.com/internetarchive/openlibrary/issues/2852

**Comment by dhruvmanila** [comment]
@cclauss Do we replace the usage of `http_cookies.SimpleCookie` and `urllib_parse` imports as well?
https://github.com/internetarchive/infogami/blob/14465ab6a2f90f329fbea7dabb80afd6cbebe8f6/infogami/infobase/client.py#L11-L12

**Comment by cclauss** [comment]
In this conversion, we are most worried about replacing calls to `urlopen()`.  While you can get at many of the urllib functions via [`requests/utils.py`](https://github.com/psf/requests/blob/master/requests/utils.py), it is often more work than it is worth.  So I would lose the `six.moves.` part of these imports and just import them from the Python 3 standard library modules.  (I believe that `pyupgrade` will automate those import transformations.)

**Comment by dhruvmanila** [comment]
Alright, got it. I will do the `isort` formatting next and then the `pyupgrade`. In the meantime, try to upgrade `urlopen` to `requests.request`. 

Also, I will start upgrading from `simplejson` to `json` builtin as well.

**Comment by cclauss** [comment]
Closed in #160
