### ISSUE TITLE
Infogami 'Nothing' class is confusing

### ISSUE THREAD

**Issue by hornc** [internetarchive/infogami#148]
Found this while investigating Open Library issue https://github.com/internetarchive/openlibrary/issues/4804
https://openlibrary.org/books/OL22299016M/Maslamah_ibn_%CA%BBAbd_al-Malik/borrow

```
from infogami.infobase.client import Nothing
a = Nothing()
ids = [a]
if not ids: print("ids is empty")
```

==> actual: nothing prints, ids is _not_ empty 
expected: the `not ids` test should be True to allow 
https://github.com/internetarchive/openlibrary/blob/bcbd90a3b259fabb0bb79e8b8c234c25bf068d00/openlibrary/core/lending.py#L312-L313
to behave correctly

but 
`print(ids) => []`

This make it hard to debug and figure out whether a list is really empty.

Visiting a borrow URL for an item without an IA identifier triggers this issue.

I wonder if this is having unintended consequences elsewhere?

This was showing up in the logs:
`TypeError: sequence item 0: expected str instance, Nothing found`

It took me waaay too long to figure out what 'Nothing' was -- took some time to click that `Nothing` wasn't a Python keyword. This was ridiculously hard to troubleshoot since this Nothing class hides all evidence of itself in its repr

**Comment by cclauss** [comment]
#109

**Comment by anandology** [comment]
On Thu, Mar 18, 2021 at 5:48 AM Charles Horn ***@***.***>
wrote:

> Found this while investigating Open Library issue
> internetarchive/openlibrary#4804
> <https://github.com/internetarchive/openlibrary/issues/4804>
>
> https://openlibrary.org/books/OL22299016M/Maslamah_ibn_%CA%BBAbd_al-Malik/borrow
>
> from infogami.infobase.client import Nothing
> a = Nothing()
> ids = [a]
> if not ids: print("ids is empty")
>
> ==> actual: nothing prints, ids is *not* empty
> expected: the not ids test should be True to allow
>
> https://github.com/internetarchive/openlibrary/blob/bcbd90a3b259fabb0bb79e8b8c234c25bf068d00/openlibrary/core/lending.py#L312-L313
> to behave correctly
>
No, that is not possible with Python. A non-empty list is always considered
as True.


> but
> print(ids) => []
>
> This make it hard to debug and figure out whether a list is really empty.
>
True. You need to fix the `__repr__` of `Nothing`.

```
   def __repr__(self): return "<Nothing>"
```

That should take care of the confusion.
