### ISSUE TITLE
Yield tests were removed in pytest 4.0 - test_doctest will be ignored

### ISSUE THREAD

**Issue by cclauss** [internetarchive/infogami#31]
[__./infogami/infobase/tests/test_doctests.py__](https://github.com/cclauss/infogami/blob/master/infogami/infobase/tests/test_doctests.py) contains yield tests.

See: https://docs.pytest.org/en/latest/deprecations.html#yield-tests

**Comment by hornc** [comment]
Fixed with 384d6c9d4c216f0f9c44c664b399ca558404f438
