### ISSUE TITLE
Travis should also run openlibrary's tests

### ISSUE THREAD

**Issue by cdrini** [internetarchive/infogami#49]
As part of testing this repo, travis should also clone the OL repo and run its tests to make sure it runs with the latest version of infogami. This will avoid issues like this: https://github.com/internetarchive/openlibrary/pull/2416#issuecomment-536223226

**Comment by cclauss** [comment]
This repo does not depend on OL but the opposite is true.  So the testing is being done in the correct way already.  This repo has standalone tests as is should.  OL which depends on this repo so its tests should involve integration between the two as it does.

**Comment by cdrini** [comment]
I agree with that in theory, but not in this specific case. Open Library is the biggest (only) user of this repo. If a bug is introduced into the source code that causes a break in functionality for Open Library, I would call that an issue with infogami. This specific break https://github.com/internetarchive/openlibrary/pull/2416#issuecomment-536223226 occurred because it wasn't clear that a method was being imported into openlibrary from infogami. I think the tests can `allow_failures`, but it would be useful to have that knowledge as early as possible. It would also make it easier to find out which commit/PR caused the regression (instead of having to `git blame` the file that was imported from infogami to see when it was last changed).

**Comment by cclauss** [comment]
Drop this repo and move all code into OL.  The monorepo will be much more efficient.

**Comment by cdrini** [comment]
Tbh, it does feel like that some times :P Although there are benefits to keeping these decoupled; even if only to alleviate mental load of people working on the ol repo.

**Comment by tfmorris** [comment]
I agree that, given the current dependency structure, it's not appropriate to be running OpenLibrary tests here.

Can we close this?
