### ISSUE TITLE
ThreadedDict issue

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/infogami#53]
https://dev.openlibrary.org/type/list?m=edit

```
<type 'exceptions.AttributeError'> at /type/list
'ThreadedDict' object has no attribute 'lang'

/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py in __call__, line 110
GET https://dev.openlibrary.org/type/list

/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/i18n.py in __call__
            print('failed to substitute (%s/%s) in language %s' % (self._namespace, self._key, web.ctx.lang), file=web.debug) ...

/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/core/templates/default_edit.html in __template__
$var title: $_.edit_title(page.name)

**Comment by mekarpeles** [comment]
@hornc + @cclaus can you two people help us debug this? This is impacting production and we're unable to easily edit some of our infogami types.

**Comment by anandology** [comment]
Looks like the issue is with the template. You can edit any document also
in the yaml format. Try:

https://dev.openlibrary.org/type/list.yaml?m=edit

**Comment by mekarpeles** [comment]
Ack, I since switched dev back to infogami `7595ae764b045c58c762d303da519e00cfe06078`

**Comment by tfmorris** [comment]
@mekarpeles What's the status of this? Fixed or not fixed?

**Comment by mekarpeles** [comment]
I think we're good for now, closing.
