### ISSUE TITLE
Is infogami/infobase/bulkupload.py used?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/infogami#93]
infogami/infobase/bulkupload.py relies on DATATYPE_REFERENCE and TYPES which I can not find in the codebase.

**Comment by dherbst** [comment]
Looks like they were removed here: https://github.com/internetarchive/infogami/commit/010c3e22e5caa9d46cf29c3220037f8170d7c1e4#diff-b57296552d8cfe175615065efe632d38826d0c28ed0e4d2b5aa28d2c18b81327L33

**Comment by cclauss** [comment]
My sense is that we should remove the files that rely on these variables and/or tdb because these files have not been run in years (or they would have errored).
